# Dependabot configuration for Zero Documentation
# This file configures Dependabot to automatically update dependencies

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "jagjeevankashid"
    assignees:
      - "jagjeevankashid"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "auto-update"
    # Group updates to reduce PR noise
    groups:
      next-js:
        patterns:
          - "next*"
          - "@next/*"
        update-types:
          - "minor"
          - "patch"
      fumadocs:
        patterns:
          - "fumadocs*"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "eslint*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific packages if needed
    # ignore:
    #   - dependency-name: "react"
    #     versions: ["18.x"]
    #   - dependency-name: "next"
    #     update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "jagjeevankashid"
    assignees:
      - "jagjeevankashid"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "auto-update"
